DROP TABLE IF EXISTS users, resources, requests;

CREATE table IF NOT EXISTS users(
    user_id bigint generated by default as identity primary key,
    ticket_series varchar(10) NOT NULL,
    ticket_number varchar(10) NOT NULL,
    name varchar(64) NOT NULL,
    ticket_start_date timestamp without time zone
);

CREATE table IF NOT EXISTS resources(
    resource_id bigint generated by default as identity primary key,
    resource_name varchar(255) NOT NULL,
    resource_quota int,
    request_accepting_begin timestamp without time zone,
    request_accepting_end timestamp without time zone,
    resource_state varchar(64) NOT NULL
);

CREATE table IF NOT EXISTS requests(
    request_id bigint generated by default as identity primary key,
    user_id  bigint REFERENCES users (user_id) ON DELETE CASCADE,
    request_type varchar NOT NULL,
    resource_location_name varchar NOT NULL,
    resource_amount int NOT NULL,
    resource_id  bigint REFERENCES resources (resource_id) ON DELETE CASCADE,
    request_state varchar NOT NULL
);

