DROP TABLE IF EXISTS users, resources, requests;

CREATE table IF NOT EXISTS users(
    ticket_series int NOT NULL,
    ticket_number int NOT NULL,
    name varchar(64) NOT NULL,
    CONSTRAINT user_id primary key (ticket_series, ticket_number)
);

CREATE table IF NOT EXISTS resources(
    resource_id bigint generated by default as identity primary key,
    resource_name varchar(255) NOT NULL,
    resource_quota int,
    request_accepting_begin timestamp without time zone,
    request_accepting_end timestamp without time zone
);
CREATE table IF NOT EXISTS requests(
    request_id bigint generated by default as identity primary key,
    request_type varchar NOT NULL,
    resource_location_name varchar NOT NULL,
    resource_amount int NOT NULL,
    resource_id  bigint REFERENCES resources (resource_id) ON DELETE CASCADE,
    user_ticket_series int NOT NULL,
    user_ticket_number int NOT NULL,
    FOREIGN KEY (user_ticket_series, user_ticket_number)
        REFERENCES users (ticket_series, ticket_number) ON DELETE CASCADE
);

