version: '3.1'
services:
  main-server:
    container_name: hunters_app
    ports:
      - "8080:8080"
    depends_on:
      - main-db
    build:
      context: .
    environment:
      - spring.datasource.url=jdbc:postgresql://main-db:5432/hunters_app_database
      - spring.datasource.username=username
      - spring.datasource.password=password
  main-db:
    image: postgres:14-alpine
    container_name: hunters_app_database
    volumes:
      - /var/lib/postgresql/data/
    ports:
        - "6541:5432"
    environment:
      - POSTGRES_DB=hunters_app_database
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
